import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

// The route table, transcribed from the old components/Router.tsx. Page files
// are route modules as they are: each already default-exports its component.
// Paths are relative to src/ (appDirectory in react-router.config.ts).
//
// A file used by more than one URL needs an explicit id; the first use keeps
// the default one.
export default [
  layout("components/layout/layout.tsx", [
    index("routes/home.tsx"),
    route("about", "pages/about.tsx"),
    route("contact", "pages/contact.tsx"),
    route("privacy", "pages/privacy.tsx"),
    route("terms", "pages/terms.tsx"),
    route("signin", "pages/signin.tsx"),
    route("signup", "pages/signup.tsx"),
    route("verify-email", "pages/verify-email.tsx"),
    route("vendor-signup", "pages/VendorSignup.tsx"),
    route("partner-signup", "pages/PartnerSignup.tsx"),
    route("forgot-password", "pages/forgot-password.tsx"),
    route("reset-password", "pages/reset-password.tsx"),
    route("gifts", "pages/gifts.tsx"),
    route("gifts/:categorySlug", "pages/gifts.tsx", { id: "gifts-categorySlug" }),
    route("shop", "pages/shop.tsx"),
    route("shop/:categorySlug", "pages/shop.tsx", { id: "shop-categorySlug" }),
    route("shop/category/:subcategorySlug", "pages/shop.tsx", { id: "shop-category-subcategorySlug" }),
    route("packages", "pages/packages.tsx"),
    route("packages/:packageId", "pages/package-detail.tsx"),
    route("gift-experiences", "routes/gift-experiences.tsx"),
    route("occasions", "pages/occasions.tsx"),
    route("occasions/:categorySlug", "pages/occasion-category.tsx"),
    route("collections", "pages/collections.tsx"),
    route("events", "pages/events.tsx"),
    route("events/:slug", "pages/event-detail.tsx"),
    route("services", "pages/services.tsx"),
    route("services/:id", "pages/service-detail.tsx"),
    route("campaigns/:id", "pages/campaign-detail.tsx"),
    route("product/:id", "pages/product-detail.tsx"),
    route("vendor/:id", "pages/vendor-detail.tsx"),
    route("cart", "pages/cart.tsx"),
    route("custom-orders", "pages/custom-orders.tsx"),
    route("custom-orders/categories", "pages/customer/CustomOrderCategories.tsx"),
    route("custom-orders/category/:categoryId", "pages/customer/CustomOrderTemplates.tsx"),
    route("offline", "routes/offline.tsx"),
    layout("routes/protected.tsx", [
      route("events/:eventId/checkout", "pages/event-checkout.tsx"),
      route("service-checkout/:serviceId", "pages/service-checkout.tsx"),
      route("service-confirmation/:orderId", "pages/service-confirmation.tsx"),
      route("service-confirmation", "pages/service-confirmation.tsx", { id: "service-confirmation" }),
      route("checkout", "pages/Checkout.tsx"),
      route("order-review", "pages/OrderReview.tsx"),
      route("wishlist", "pages/Wishlist.tsx"),
      route("custom-orders/template/:templateId", "pages/customer/CreateCustomOrder.tsx"),
      route("custom-orders/template/:templateId/shipping", "pages/customer/CustomOrderShipping.tsx"),
      route("payment/stripe", "pages/stripe-payment.tsx"),
      route("payment/chapa", "pages/chapa-payment.tsx"),
      route("payment/chapa/callback", "pages/payment-success.tsx"),
      route("payment/telebirr", "pages/telebirr-payment.tsx"),
      route("payment/telebirr/return", "pages/telebirr-return.tsx"),
      route("payment-success", "pages/payment-success.tsx", { id: "payment-success" }),
      route("service-order-success", "pages/service-order-success.tsx"),
      route("event-order-success", "pages/event-order-success.tsx"),
      route("my-tickets", "pages/my-event-tickets.tsx"),
      route("my-orders", "pages/MyOrders.tsx"),
      route("track/:orderId", "pages/TrackOrder.tsx"),
      route("my-service-orders", "pages/my-service-orders.tsx"),
      route("my-service-orders/:orderId", "pages/track-service-order.tsx"),
      route("my-custom-orders", "pages/customer/MyCustomOrders.tsx"),
      route("my-custom-orders/:orderId", "pages/customer/CustomerCustomOrderDetail.tsx"),
      route("profile", "pages/Profile.tsx"),
    ]),
    route("*", "pages/not-found.tsx"),
  ]),
  route("vendor", "routes/vendor.tsx", [
    index("pages/vendor/VendorOverview.tsx"),
    route("products", "pages/vendor/VendorProductsPage.tsx"),
    route("products/new", "pages/vendor/CreateProduct.tsx"),
    route("products/:id", "pages/vendor/VendorProductDetail.tsx"),
    route("products/:id/edit", "pages/vendor/EditProduct.tsx"),
    route("products/:id/price", "pages/vendor/ProductPriceUpdate.tsx"),
    route("events", "pages/vendor/VendorEventsPage.tsx"),
    route("events/new", "pages/vendor/CreateEvent.tsx"),
    route("events/:id", "pages/vendor/VendorEventDetail.tsx"),
    route("events/:id/edit", "pages/vendor/EditEvent.tsx"),
    route("events/:id/price", "pages/vendor/EventPriceUpdate.tsx"),
    route("services", "pages/vendor/VendorServicesPage.tsx"),
    route("services/new", "pages/vendor/CreateService.tsx"),
    route("services/:id", "pages/vendor/VendorServiceDetail.tsx"),
    route("services/:id/edit", "pages/vendor/EditService.tsx"),
    route("service-orders", "pages/vendor/VendorServiceOrders.tsx"),
    route("service-calendar", "pages/vendor/VendorServiceCalendar.tsx"),
    route("product-orders", "pages/vendor/VendorProductOrders.tsx"),
    route("packages", "pages/vendor/VendorPackagesPage.tsx"),
    route("package-orders", "pages/vendor/VendorPackageOrders.tsx"),
    route("discounts", "pages/vendor/VendorDiscountsPage.tsx"),
    route("discounts/new", "pages/vendor/CreateDiscount.tsx"),
    route("discounts/:id", "pages/vendor/VendorDiscountDetail.tsx"),
    route("discounts/:id/edit", "pages/vendor/EditDiscount.tsx"),
    route("discounts/:id/usages", "pages/vendor/VendorDiscountUsages.tsx"),
    route("campaigns", "pages/vendor/VendorCampaignsPage.tsx"),
    route("custom-templates", "pages/vendor/VendorCustomTemplates.tsx"),
    route("custom-templates/new", "pages/vendor/CreateCustomTemplate.tsx"),
    route("custom-templates/:id", "pages/vendor/VendorCustomTemplateDetail.tsx"),
    route("custom-orders", "pages/vendor/VendorCustomOrders.tsx"),
    route("custom-orders/:orderId", "pages/vendor/VendorCustomOrderDetail.tsx"),
    route("check-in", "pages/vendor/VendorCheckInPage.tsx"),
    route("payments", "pages/vendor/VendorPaymentsPage.tsx"),
    route("payments/chapa", "pages/vendor/ChapaOnboarding.tsx"),
    route("onboarding/return", "pages/vendor/StripeOnboardingReturn.tsx"),
    route("onboarding/refresh", "pages/vendor/StripeOnboardingRefresh.tsx"),
    route("requests", "pages/vendor/VendorRequests.tsx"),
    route("settings", "pages/vendor/VendorSettingsPage.tsx"),
    route("resubmit", "pages/vendor/VendorResubmitPage.tsx"),
  ]),
  route("admin", "routes/admin.tsx", [
    index("pages/admin/AdminDashboard.tsx"),
    route("users", "pages/admin/AdminUsers.tsx"),
    route("vendors", "pages/admin/AdminVendors.tsx"),
    route("products", "pages/admin/AdminProducts.tsx"),
    route("services", "pages/admin/AdminServices.tsx"),
    route("events", "pages/admin/AdminEvents.tsx"),
    route("categories", "pages/admin/AdminCategories.tsx"),
    route("subcategories", "pages/admin/AdminSubcategories.tsx"),
    route("tax", "pages/admin/AdminTax.tsx"),
    route("currency", "pages/admin/AdminCurrency.tsx"),
    route("delivery", "pages/admin/AdminDelivery.tsx"),
    route("campaigns", "pages/admin/AdminCampaigns.tsx"),
    route("broadcasts", "pages/admin/AdminBroadcasts.tsx"),
    route("search-analytics", "pages/admin/AdminSearchAnalytics.tsx"),
    route("campaign-participations", "pages/admin/AdminCampaignParticipations.tsx"),
    route("featured-ads", "pages/admin/AdminFeaturedAds.tsx"),
    route("custom-templates", "pages/admin/AdminCustomTemplates.tsx"),
    route("orders", "pages/admin/AdminOrders.tsx"),
    route("custom-orders", "pages/admin/AdminCustomOrders.tsx"),
    route("payment-methods", "pages/admin/AdminPaymentMethods.tsx"),
    route("refunds", "pages/admin/AdminRefunds.tsx"),
    route("vendor-payouts", "pages/admin/AdminVendorPayout.tsx"),
    route("commission", "pages/admin/AdminCommission.tsx"),
    route("wallet", "pages/admin/AdminWallet.tsx"),
    route("roles", "pages/admin/AdminRoles.tsx"),
    route("permissions", "pages/admin/AdminPermissions.tsx"),
    route("partnership-applications", "pages/admin/AdminPartnershipApplications.tsx"),
    route("partnership-applications/reports", "pages/admin/AdminSupplierReports.tsx"),
  ]),
  route("delivery", "routes/delivery.tsx", [
    index("pages/delivery/DeliveryDashboard.tsx"),
    route("available-orders", "pages/delivery/AvailableOrders.tsx"),
    route("assignments", "pages/delivery/DeliveryAssignments.tsx"),
    route("assignments/:assignmentId", "pages/delivery/DeliveryAssignmentDetail.tsx"),
    route("history", "pages/delivery/DeliveryHistory.tsx"),
    route("profile", "pages/delivery/DeliveryProfile.tsx"),
  ]),
] satisfies RouteConfig;
